spring:
  redis:
    host: 192.168.25.110
    port: 6379
    timeout: 6000ms # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10  # 连接池中的最大空闲连接
        min-idle: 5  # 连接池中的最小空闲连接
  datasource:
    username: root
    password: root
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///test?characterEncoding=utf8&serverTimezone=UTC
#mybatis:
#  type-aliases-package: cn.test.springdataredistest01.entities
#  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
#  config-location: classpath:mybatis/mybatis-config.xml
springbootlearn:
  redis:
    open: true
